export type Bindings = {
  DB: D1Database
  VAULT_OBJECTS: R2Bucket
  HONOWARDEN_ALLOWED_EMAILS?: string
  HONOWARDEN_BOOTSTRAP_ENABLED?: string
  HONOWARDEN_BOOTSTRAP_TOKEN?: string
  HONOWARDEN_AUDIT_LOGS?: string
  HONOWARDEN_ENV?: string
  HONOWARDEN_GLOBAL_REQUEST_QUOTA?: string
  HONOWARDEN_INQUIRY_DOMAIN?: string
  HONOWARDEN_INQUIRY_MAILBOXES?: string
  HONOWARDEN_ACCESS_TOKEN_ACTIVE_KID?: string
  HONOWARDEN_ACCESS_TOKEN_ACTIVE_SECRET?: string
  HONOWARDEN_ACCESS_TOKEN_PREVIOUS_KEYS?: string
  HONOWARDEN_TOKEN_SECRET?: string
  HONOWARDEN_TOTP_SECRET?: string
}
